<?php require('template/header.phtml') ?>
    <div id = "findDVD">
        <h3>Filter by DVD Name</h3>
        <form action = "<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>" method="post">
            <label>DVD Name:</label>
            <input type = "text" name = "dvdName" value = "<?php echo $_POST['dvdName']; ?>" required/>
            <input type = "submit" value = "Search" name = "searchDVD"/>
        </form>
    </div>

<?php require('template/footer.phtml') ?>