<?php require('template/header.phtml') ?>
<html>
<div id="filters"
     <div>
         <h3>All Filters</h3>
         <h2>Cast</h2>
         <p><a href="cast.php">Search by Cast Member</a></p> <br>

         <h2>Director</h2>
         <p><a href="director.php">Search by Director</a></p> <br>

         <h2>DVD Name</h2>
         <p><a href="dvdname.php">Search by DVD Name</a></p> <br>

         <h2>Genre</h2>
         <p><a href="genre.php">Search by Genre</a></p> <br>

         <h2>Price</h2>
         <p><a href="price.php">Search by Price</a></p> <br>

         <h2>Year</h2>
         <p><a href="year.php">Search by Year</p></a> <br>
     </div>
</html>

<?php require('template/footer.phtml') ?>
