<?php require('template/header.phtml') ?>

<h3>Welcome to The DVD Shack</h3><br>

<p>
    To see all of the DVD's we have on offer please click <a href="dvd.php"><i>here</i></a>.<br>
</p>

<p>
    In order to rent from us it is required that you have an account.
    <a href="login.php"><i>Please log in</i></a> or <a href="register.php"><i>sign up here</i></a>.<br>
</p>

<p>
    <b> &#9888; Please be warned, we only have <u>one</u> copy of each DVD</b>. &#9888;<br>
</p>

<p>
    <i>This site may use cookies. For more information see your browser or
        <a href="https://ico.org.uk/for-the-public/online/cookies/">ico.org.uk/cookies</a></i>
</p>
<?php require('template/footer.phtml') ?>
