<?php require('template/header.phtml'); ?>

<div id="login">
    <h3>New here? please <a href="register.php"><i>sign up</i></a>.</h3>
    <h4>Already have an account? please log in: </h4>
    <form action = "<?php echo $_SERVER['PHP_SELF']; ?>" method ="post">
        <label>Username</label>
        <input type="email" name="userName" placeholder="User Name" value="<?php echo $_POST['userName']; ?>" required/>

        <label>Password</label>
        <input type="password" name="password" placeholder="Password" value="<?php echo $_POST['password']; ?>" required/>

        <input type = "submit" value = "Sign In" name = "signIn"/>
        <input type = "submit" value = "Sign Out" name = "SignOut"/>
    </form>
</div>

<?php if(isset($_POST['SignOut']))
{
    session_destroy();
    echo 'You have logged out';
    session_start();
}

require('template/footer.phtml'); ?>
