<?php require('template/header.phtml') ?>

<div id = "findPrice">
    <h3>Filter by Price</h3>
    <form action = "<?php echo htmlspecialchars($_SERVER['PHP_SELF']);?>" method="post">
        <label>Price: £</label>
        <input type = "text" name = "price" value="<?php echo $_POST['price'];?>" required/>
        <input type = "submit" value = "Search" name = "searchPrice"/>
    </form>
</div>

<?php require('template/footer.phtml') ?>
