</div>
<html>
<body>
<div class-"row">
        <div id="footer" class="col-xs-12">
            <p><a href= "mailto:j.pollitt@edu.salford.ac.uk?Subject=The%20DVD%20Shack" target="_blank">TheDVDShack&copy;</a></p>
            <p>2016</p>
        </div>

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
<script src="js/bootstrap.min.js"></script>
</body>
</html>