<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">


    <!-- Bootstrap core CSS -->
    <link href="/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="/css/bootstrap-theme.css" rel="stylesheet">
    <link href="/css/my-style.css" rel="stylesheet">

    <title>The DVD Shack - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<div class="container">
        <div  class="row">
            <div id="title" class="col-xs-12">
                <a href = "index.php">
                <img src="images/dvdshack.png" alt="The DVD Shack" height="200" width="200"/> </a>
                    <div class="pull-right"> <h1><?php echo $view->pageTitle ?> </h1></div>
            </div>

    <div class="row" role ="navigation">
        <div id="menu" class="col-xs-6 col-sm-3 col-md-2">
            <ul class="nav navbar_default nav-stacked">
            <li><a href="index.php">Home</a></li>
            <li><a href="login.php">Login</a></li>
            <li><a href="dvd.php">All DVD's</a></li>
            <li><a href="filter.php">Filters</a></li>
            <li><a href="basket.php">Basket</a></li>
            <li><a href="admin.php">Admin</a></li>
        </ul>
       </div>

    <div id="content" class="col-xs-6 col-sm-9 col-md-10">